export default {
  "selectNode": {
    "title": "请选择可处理的节点",
    "showNodeMask": false,
    "ListName": {
      "title": "",
      "personName": "",
      "headPic": "",
      "createTime": ""
    },
    "NodeList": [],
    "detailData": null
  },
  "detail": {
    "detailTitleData": {
      "openPrint": true,
      "status": {},
      "mediaList": [],
      "creator": {
        "userId": "13821f42790d0819757d4d306d1ac8a5",
        "personName": "郑佳娜",
        "headPic": "http://shp.qpic.cn/bizmp/ck4hSGq23RiauEtDg0w7H4PSw7sHCVgaZrmxxey29oqiaExHKDho5yyw/100",
        "createPerson": "13821f42790d0819757d4d306d1ac8a5"
      },
      "tips": "zjn_审批固定",
      "title": "郑佳娜_20180801_固定流程123",
      "auditStatus": "审批中",
      "createTime": "2018-08-01 18:04:52",
      "personName": "郑佳娜",
      "content": "固定流程",
      "picList": [],
      "orgId": "b17efb43-292e-4cc9-ac5d-0b46bce059c4"
    },
    "detailData": {
      "auditStatus": "审批中",
      "ccPersons": [],
      "closePerson": "",
      "closeReason": "",
      "closeTime": null,
      "commentCount": 3,
      "content": "固定流程",
      "createTime": "2018-08-01 18:04:52",
      "creator": "13821f42790d0819757d4d306d1ac8a5",
      "currentNodeId": "becf3615-0c8e-4e98-8936-483c1c59e6ce",
      "flowId": "e5fd74529f3342cda8f56abcfdcd6b74",
      "headPic": "http://shp.qpic.cn/bizmp/ck4hSGq23RiauEtDg0w7H4PSw7sHCVgaZrmxxey29oqiaExHKDho5yyw/100",
      "isFree": "0",
      "isover": "",
      "moveapproveId": "3e900adf-30d3-481f-8f8d-73b4908080d7",
      "moveapproveStatus": "1",
      "moveapproveType": "917fa519-d0d9-42b3-9cbf-86d5463061a2",
      "notRead": "",
      "orgId": "b17efb43-292e-4cc9-ac5d-0b46bce059c4",
      "personName": "郑佳娜",
      "picList": [],
      "title": "郑佳娜_20180801_固定流程123",
      "toPersons": [
        {
          "createPerson": "13821f42790d0819757d4d306d1ac8a5",
          "createTime": {
            "date": 1,
            "day": 3,
            "hours": 18,
            "minutes": 4,
            "month": 7,
            "seconds": 53,
            "time": 1533117893000,
            "timezoneOffset": -480,
            "year": 118
          },
          "headPic": "http://shp.qpic.cn/bizmp/ck4hSGq23Riao6KeuOJ254Qh4K8JHMaPqAKolhy5CVyasJzBbqol3mQ/100",
          "mobile": "",
          "moveapproveId": "3e900adf-30d3-481f-8f8d-73b4908080d7",
          "personName": "卢鑫哲",
          "recipientId": "68b33bb308264f11a47e7dad75516d54",
          "userId": "7e02a1e06c2a320a8306b3841a286844",
          "userType": "0",
          "wxUserId": "luxinzhe"
        },
        {
          "createPerson": "13821f42790d0819757d4d306d1ac8a5",
          "createTime": {
            "date": 1,
            "day": 3,
            "hours": 18,
            "minutes": 4,
            "month": 7,
            "seconds": 53,
            "time": 1533117893000,
            "timezoneOffset": -480,
            "year": 118
          },
          "headPic": "http://shp.qpic.cn/bizmp/ck4hSGq23RiaXrPGkj1HGs94CKIicicAkQlXqxz2V6ic3K8TmbeWQqj5sg/100",
          "mobile": "",
          "moveapproveId": "3e900adf-30d3-481f-8f8d-73b4908080d7",
          "personName": "曾佳英",
          "recipientId": "c7e3e55548e345a18f36307f7465fde0",
          "userId": "da3fed20764d38ce1672d7bb610908ab",
          "userType": "0",
          "wxUserId": "zengjiaying"
        }
      ],
      "typeName": "zjn_审批固定"
    },
    "mediaList": [],
    "FlowAudit": null,
    "approveVo": null,
    "approveDialogShow": false
  },
  "flowUserSelected": {
    "isBranchFlow": false,
    "isBranchNode": false,
    "flowId": "e5fd74529f3342cda8f56abcfdcd6b74",
    "currentNodeId": "becf3615-0c8e-4e98-8936-483c1c59e6ce",
    "nextNodeId": "",
    "defaultNextNodeId": "",
    "parallelNextNodeIds": "",
    "flowList": [],
    "nextNodeList": [],
    "appointNodeAndUserVOList": [],
    "FlowAuditList": [
      {
        "appointNodeAndUserVOList": [],
        "auditLeave": false,
        "auditUserList": [
          {
            "attribute": 0,
            "birthday": "",
            "childrenList": [],
            "corpId": "",
            "createTime": "",
            "departmentName": "",
            "deptId": "",
            "email": "",
            "entryTime": "",
            "headPic": "http://shp.qpic.cn/bizmp/ck4hSGq23RiaXrPGkj1HGs94CKIicicAkQlXqxz2V6ic3K8TmbeWQqj5sg/100",
            "id": "",
            "isTop": 0,
            "leaveTime": "",
            "lunarCalendar": "",
            "mobile": "",
            "orgId": "b17efb43-292e-4cc9-ac5d-0b46bce059c4",
            "personName": "曾佳英",
            "pinyin": "",
            "position": "",
            "sex": "",
            "shorMobile": "",
            "updateTime": "",
            "userId": "da3fed20764d38ce1672d7bb610908ab",
            "userStatus": "",
            "weixinNum": "",
            "wxUserId": "zengjiaying"
          }
        ],
        "audtiFlag": "1",
        "fieldContralList": [],
        "flowNodeItemKeys": "",
        "formerHandlers": "",
        "isAlreadyAudit": 0,
        "isBranchNode": false,
        "isChoise": "2",
        "nextAuditList": [
          {
            "attribute": 0,
            "birthday": "",
            "childrenList": [],
            "corpId": "wx05ab253814890c89",
            "createTime": "",
            "departmentName": "",
            "deptId": "",
            "email": "",
            "entryTime": "",
            "headPic": "http://shp.qpic.cn/bizmp/ck4hSGq23Riao6KeuOJ254Qh4K8JHMaPqAKolhy5CVyasJzBbqol3mQ/100",
            "id": "7e0931e06caa320a8606b2348a196844",
            "isTop": 0,
            "leaveTime": "",
            "lunarCalendar": "",
            "mobile": "15259507256",
            "orgId": "b17efb43-292e-4cc9-ac5d-0b46bce059c4",
            "personName": "卢鑫哲",
            "pinyin": "",
            "position": "",
            "sex": "",
            "shorMobile": "",
            "updateTime": "",
            "userId": "7e02a1e06c2a320a8306b3841a286844",
            "userStatus": "2",
            "weixinNum": "",
            "wxUserId": "luxinzhe"
          },
          {
            "attribute": 0,
            "birthday": "",
            "childrenList": [],
            "corpId": "wx05ab253814890c89",
            "createTime": "",
            "departmentName": "",
            "deptId": "",
            "email": "",
            "entryTime": "",
            "headPic": "http://shp.qpic.cn/bizmp/ck4hSGq23RgFSf7iadwB9T1jGibNabgp7VAfPlzoIicces7fJIMICZlDA/100",
            "id": "1dd9da6a-fee9-46eb-864e-53fbca77b96d",
            "isTop": 0,
            "leaveTime": "",
            "lunarCalendar": "",
            "mobile": "15989131328",
            "orgId": "b17efb43-292e-4cc9-ac5d-0b46bce059c4",
            "personName": "陈飞雄",
            "pinyin": "",
            "position": "",
            "sex": "",
            "shorMobile": "",
            "updateTime": "",
            "userId": "cbbf7e9ab38549d3822476feabefdec2",
            "userStatus": "2",
            "weixinNum": "",
            "wxUserId": "qy_15989131328"
          }
        ],
        "nextChoiseUserNodeId": "",
        "nextNodeId": "",
        "nodeHandleType": "",
        "nodeType": "1",
        "parseAddSignVO": {
          "backSignPersonMap": null,
          "canAddBackSign": 0,
          "canAddConterSign": 0,
          "canAddFrontSign": 0,
          "canAddSign": 0,
          "conterSignPersonMap": null,
          "frontSignPersonMap": null
        },
        "userHandSignImg": "",
        "vo": {
          "addSign": null,
          "appointEndDepartmentIds": "",
          "auditAccount": "7e02a1e06c2a320a8306b3841a286844",
          "auditStatus": "0",
          "createTime": "2018-08-01 18:04:52",
          "creator": "13821f42790d0819757d4d306d1ac8a5",
          "defaultNextNodeId": "",
          "ext1": "",
          "flowId": "e5fd74529f3342cda8f56abcfdcd6b74",
          "flowName": "",
          "handleAccounts": "da3fed20764d38ce1672d7bb610908ab|",
          "havaBranch": 0,
          "id": "5c761c5ad9da445fa953c3151a47a867",
          "isAddCountersign": 0,
          "isAutomaticAudit": 0,
          "isCanEnd": "0",
          "isChoice": "1",
          "isExistTag": 0,
          "isLading": "2",
          "isQuery": "0",
          "isSign": "0",
          "isSoter": 0,
          "isTimeSet": 0,
          "isUseHandWriteSign": 0,
          "isUsePresetSign": 0,
          "nodeId": "becf3615-0c8e-4e98-8936-483c1c59e6ce",
          "nodeName": "固定会签",
          "nodeRemark": "",
          "nodeSoft": 1,
          "nodeStatus": "1",
          "nodeType": "1",
          "orgId": "b17efb43-292e-4cc9-ac5d-0b46bce059c4",
          "reason": "",
          "refId": "3e900adf-30d3-481f-8f8d-73b4908080d7",
          "upNodeId": "",
          "updateTime": "2018-08-01 18:05:12"
        },
        "nodeId": "",
        "startAuditList": {
          "show": true,
          "selectType": {
            "id": "userId",
            "name": "personName",
            "headpic": "headPic",
            "type": "user"
          },
          "userSelected": [],
          "flowUserList": [
            [
              {
                "attribute": 0,
                "birthday": "",
                "childrenList": [],
                "corpId": "wx05ab253814890c89",
                "createTime": "",
                "departmentName": "",
                "deptId": "",
                "email": "",
                "entryTime": "",
                "headPic": "http://shp.qpic.cn/bizmp/ck4hSGq23Riao6KeuOJ254Qh4K8JHMaPqAKolhy5CVyasJzBbqol3mQ/100",
                "id": "7e0931e06caa320a8606b2348a196844",
                "isTop": 0,
                "leaveTime": "",
                "lunarCalendar": "",
                "mobile": "15259507256",
                "orgId": "b17efb43-292e-4cc9-ac5d-0b46bce059c4",
                "personName": "卢鑫哲",
                "pinyin": "",
                "position": "",
                "sex": "",
                "shorMobile": "",
                "updateTime": "",
                "userId": "7e02a1e06c2a320a8306b3841a286844",
                "userStatus": "2",
                "weixinNum": "",
                "wxUserId": "luxinzhe"
              },
              {
                "attribute": 0,
                "birthday": "",
                "childrenList": [],
                "corpId": "wx05ab253814890c89",
                "createTime": "",
                "departmentName": "",
                "deptId": "",
                "email": "",
                "entryTime": "",
                "headPic": "http://shp.qpic.cn/bizmp/ck4hSGq23RgFSf7iadwB9T1jGibNabgp7VAfPlzoIicces7fJIMICZlDA/100",
                "id": "1dd9da6a-fee9-46eb-864e-53fbca77b96d",
                "isTop": 0,
                "leaveTime": "",
                "lunarCalendar": "",
                "mobile": "15989131328",
                "orgId": "b17efb43-292e-4cc9-ac5d-0b46bce059c4",
                "personName": "陈飞雄",
                "pinyin": "",
                "position": "",
                "sex": "",
                "shorMobile": "",
                "updateTime": "",
                "userId": "cbbf7e9ab38549d3822476feabefdec2",
                "userStatus": "2",
                "weixinNum": "",
                "wxUserId": "qy_15989131328"
              }
            ]
          ],
          "assignRange": true,
          "isCanEdit": true,
          "isCanDelete": true,
          "defaultAllSelect": true
        }
      }
    ],
    "nodeInfo": [
      {
        "appointNodeAndUserVOList": [],
        "auditLeave": false,
        "auditUserList": [
          {
            "attribute": 0,
            "birthday": "",
            "childrenList": [],
            "corpId": "",
            "createTime": "",
            "departmentName": "",
            "deptId": "",
            "email": "",
            "entryTime": "",
            "headPic": "http://shp.qpic.cn/bizmp/ck4hSGq23RiaXrPGkj1HGs94CKIicicAkQlXqxz2V6ic3K8TmbeWQqj5sg/100",
            "id": "",
            "isTop": 0,
            "leaveTime": "",
            "lunarCalendar": "",
            "mobile": "",
            "orgId": "b17efb43-292e-4cc9-ac5d-0b46bce059c4",
            "personName": "曾佳英",
            "pinyin": "",
            "position": "",
            "sex": "",
            "shorMobile": "",
            "updateTime": "",
            "userId": "da3fed20764d38ce1672d7bb610908ab",
            "userStatus": "",
            "weixinNum": "",
            "wxUserId": "zengjiaying"
          }
        ],
        "audtiFlag": "1",
        "fieldContralList": [],
        "flowNodeItemKeys": "",
        "formerHandlers": "",
        "isAlreadyAudit": 0,
        "isBranchNode": false,
        "isChoise": "2",
        "nextAuditList": [
          {
            "attribute": 0,
            "birthday": "",
            "childrenList": [],
            "corpId": "wx05ab253814890c89",
            "createTime": "",
            "departmentName": "",
            "deptId": "",
            "email": "",
            "entryTime": "",
            "headPic": "http://shp.qpic.cn/bizmp/ck4hSGq23Riao6KeuOJ254Qh4K8JHMaPqAKolhy5CVyasJzBbqol3mQ/100",
            "id": "7e0931e06caa320a8606b2348a196844",
            "isTop": 0,
            "leaveTime": "",
            "lunarCalendar": "",
            "mobile": "15259507256",
            "orgId": "b17efb43-292e-4cc9-ac5d-0b46bce059c4",
            "personName": "卢鑫哲",
            "pinyin": "",
            "position": "",
            "sex": "",
            "shorMobile": "",
            "updateTime": "",
            "userId": "7e02a1e06c2a320a8306b3841a286844",
            "userStatus": "2",
            "weixinNum": "",
            "wxUserId": "luxinzhe"
          },
          {
            "attribute": 0,
            "birthday": "",
            "childrenList": [],
            "corpId": "wx05ab253814890c89",
            "createTime": "",
            "departmentName": "",
            "deptId": "",
            "email": "",
            "entryTime": "",
            "headPic": "http://shp.qpic.cn/bizmp/ck4hSGq23RgFSf7iadwB9T1jGibNabgp7VAfPlzoIicces7fJIMICZlDA/100",
            "id": "1dd9da6a-fee9-46eb-864e-53fbca77b96d",
            "isTop": 0,
            "leaveTime": "",
            "lunarCalendar": "",
            "mobile": "15989131328",
            "orgId": "b17efb43-292e-4cc9-ac5d-0b46bce059c4",
            "personName": "陈飞雄",
            "pinyin": "",
            "position": "",
            "sex": "",
            "shorMobile": "",
            "updateTime": "",
            "userId": "cbbf7e9ab38549d3822476feabefdec2",
            "userStatus": "2",
            "weixinNum": "",
            "wxUserId": "qy_15989131328"
          }
        ],
        "nextChoiseUserNodeId": "",
        "nextNodeId": "",
        "nodeHandleType": "",
        "nodeType": "1",
        "parseAddSignVO": {
          "backSignPersonMap": null,
          "canAddBackSign": 0,
          "canAddConterSign": 0,
          "canAddFrontSign": 0,
          "canAddSign": 0,
          "conterSignPersonMap": null,
          "frontSignPersonMap": null
        },
        "userHandSignImg": "",
        "vo": {
          "addSign": null,
          "appointEndDepartmentIds": "",
          "auditAccount": "7e02a1e06c2a320a8306b3841a286844",
          "auditStatus": "0",
          "createTime": "2018-08-01 18:04:52",
          "creator": "13821f42790d0819757d4d306d1ac8a5",
          "defaultNextNodeId": "",
          "ext1": "",
          "flowId": "e5fd74529f3342cda8f56abcfdcd6b74",
          "flowName": "",
          "handleAccounts": "da3fed20764d38ce1672d7bb610908ab|",
          "havaBranch": 0,
          "id": "5c761c5ad9da445fa953c3151a47a867",
          "isAddCountersign": 0,
          "isAutomaticAudit": 0,
          "isCanEnd": "0",
          "isChoice": "1",
          "isExistTag": 0,
          "isLading": "2",
          "isQuery": "0",
          "isSign": "0",
          "isSoter": 0,
          "isTimeSet": 0,
          "isUseHandWriteSign": 0,
          "isUsePresetSign": 0,
          "nodeId": "becf3615-0c8e-4e98-8936-483c1c59e6ce",
          "nodeName": "固定会签",
          "nodeRemark": "",
          "nodeSoft": 1,
          "nodeStatus": "1",
          "nodeType": "1",
          "orgId": "b17efb43-292e-4cc9-ac5d-0b46bce059c4",
          "reason": "",
          "refId": "3e900adf-30d3-481f-8f8d-73b4908080d7",
          "upNodeId": "",
          "updateTime": "2018-08-01 18:05:12"
        },
        "nodeId": "",
        "startAuditList": {
          "show": true,
          "selectType": {
            "id": "userId",
            "name": "personName",
            "headpic": "headPic",
            "type": "user"
          },
          "userSelected": [],
          "flowUserList": [
            [
              {
                "attribute": 0,
                "birthday": "",
                "childrenList": [],
                "corpId": "wx05ab253814890c89",
                "createTime": "",
                "departmentName": "",
                "deptId": "",
                "email": "",
                "entryTime": "",
                "headPic": "http://shp.qpic.cn/bizmp/ck4hSGq23Riao6KeuOJ254Qh4K8JHMaPqAKolhy5CVyasJzBbqol3mQ/100",
                "id": "7e0931e06caa320a8606b2348a196844",
                "isTop": 0,
                "leaveTime": "",
                "lunarCalendar": "",
                "mobile": "15259507256",
                "orgId": "b17efb43-292e-4cc9-ac5d-0b46bce059c4",
                "personName": "卢鑫哲",
                "pinyin": "",
                "position": "",
                "sex": "",
                "shorMobile": "",
                "updateTime": "",
                "userId": "7e02a1e06c2a320a8306b3841a286844",
                "userStatus": "2",
                "weixinNum": "",
                "wxUserId": "luxinzhe"
              },
              {
                "attribute": 0,
                "birthday": "",
                "childrenList": [],
                "corpId": "wx05ab253814890c89",
                "createTime": "",
                "departmentName": "",
                "deptId": "",
                "email": "",
                "entryTime": "",
                "headPic": "http://shp.qpic.cn/bizmp/ck4hSGq23RgFSf7iadwB9T1jGibNabgp7VAfPlzoIicces7fJIMICZlDA/100",
                "id": "1dd9da6a-fee9-46eb-864e-53fbca77b96d",
                "isTop": 0,
                "leaveTime": "",
                "lunarCalendar": "",
                "mobile": "15989131328",
                "orgId": "b17efb43-292e-4cc9-ac5d-0b46bce059c4",
                "personName": "陈飞雄",
                "pinyin": "",
                "position": "",
                "sex": "",
                "shorMobile": "",
                "updateTime": "",
                "userId": "cbbf7e9ab38549d3822476feabefdec2",
                "userStatus": "2",
                "weixinNum": "",
                "wxUserId": "qy_15989131328"
              }
            ]
          ],
          "assignRange": true,
          "isCanEdit": true,
          "isCanDelete": true,
          "defaultAllSelect": true
        }
      }
    ],
    "FlowAuditUserBoxShow": false,
    "flowApproveDialogShow": false,
    "FlowAuditUser": [
      {
        "appointNodeAndUserVOList": [],
        "auditLeave": false,
        "auditUserList": [
          {
            "attribute": 0,
            "birthday": "",
            "childrenList": [],
            "corpId": "",
            "createTime": "",
            "departmentName": "",
            "deptId": "",
            "email": "",
            "entryTime": "",
            "headPic": "http://shp.qpic.cn/bizmp/ck4hSGq23RiaXrPGkj1HGs94CKIicicAkQlXqxz2V6ic3K8TmbeWQqj5sg/100",
            "id": "",
            "isTop": 0,
            "leaveTime": "",
            "lunarCalendar": "",
            "mobile": "",
            "orgId": "b17efb43-292e-4cc9-ac5d-0b46bce059c4",
            "personName": "曾佳英",
            "pinyin": "",
            "position": "",
            "sex": "",
            "shorMobile": "",
            "updateTime": "",
            "userId": "da3fed20764d38ce1672d7bb610908ab",
            "userStatus": "",
            "weixinNum": "",
            "wxUserId": "zengjiaying"
          }
        ],
        "audtiFlag": "1",
        "fieldContralList": [],
        "flowNodeItemKeys": "",
        "formerHandlers": "",
        "isAlreadyAudit": 0,
        "isBranchNode": false,
        "isChoise": "2",
        "nextAuditList": [
          {
            "attribute": 0,
            "birthday": "",
            "childrenList": [],
            "corpId": "wx05ab253814890c89",
            "createTime": "",
            "departmentName": "",
            "deptId": "",
            "email": "",
            "entryTime": "",
            "headPic": "http://shp.qpic.cn/bizmp/ck4hSGq23Riao6KeuOJ254Qh4K8JHMaPqAKolhy5CVyasJzBbqol3mQ/100",
            "id": "7e0931e06caa320a8606b2348a196844",
            "isTop": 0,
            "leaveTime": "",
            "lunarCalendar": "",
            "mobile": "15259507256",
            "orgId": "b17efb43-292e-4cc9-ac5d-0b46bce059c4",
            "personName": "卢鑫哲",
            "pinyin": "",
            "position": "",
            "sex": "",
            "shorMobile": "",
            "updateTime": "",
            "userId": "7e02a1e06c2a320a8306b3841a286844",
            "userStatus": "2",
            "weixinNum": "",
            "wxUserId": "luxinzhe"
          },
          {
            "attribute": 0,
            "birthday": "",
            "childrenList": [],
            "corpId": "wx05ab253814890c89",
            "createTime": "",
            "departmentName": "",
            "deptId": "",
            "email": "",
            "entryTime": "",
            "headPic": "http://shp.qpic.cn/bizmp/ck4hSGq23RgFSf7iadwB9T1jGibNabgp7VAfPlzoIicces7fJIMICZlDA/100",
            "id": "1dd9da6a-fee9-46eb-864e-53fbca77b96d",
            "isTop": 0,
            "leaveTime": "",
            "lunarCalendar": "",
            "mobile": "15989131328",
            "orgId": "b17efb43-292e-4cc9-ac5d-0b46bce059c4",
            "personName": "陈飞雄",
            "pinyin": "",
            "position": "",
            "sex": "",
            "shorMobile": "",
            "updateTime": "",
            "userId": "cbbf7e9ab38549d3822476feabefdec2",
            "userStatus": "2",
            "weixinNum": "",
            "wxUserId": "qy_15989131328"
          }
        ],
        "nextChoiseUserNodeId": "",
        "nextNodeId": "",
        "nodeHandleType": "",
        "nodeType": "1",
        "parseAddSignVO": {
          "backSignPersonMap": null,
          "canAddBackSign": 0,
          "canAddConterSign": 0,
          "canAddFrontSign": 0,
          "canAddSign": 0,
          "conterSignPersonMap": null,
          "frontSignPersonMap": null
        },
        "userHandSignImg": "",
        "vo": {
          "addSign": null,
          "appointEndDepartmentIds": "",
          "auditAccount": "7e02a1e06c2a320a8306b3841a286844",
          "auditStatus": "0",
          "createTime": "2018-08-01 18:04:52",
          "creator": "13821f42790d0819757d4d306d1ac8a5",
          "defaultNextNodeId": "",
          "ext1": "",
          "flowId": "e5fd74529f3342cda8f56abcfdcd6b74",
          "flowName": "",
          "handleAccounts": "da3fed20764d38ce1672d7bb610908ab|",
          "havaBranch": 0,
          "id": "5c761c5ad9da445fa953c3151a47a867",
          "isAddCountersign": 0,
          "isAutomaticAudit": 0,
          "isCanEnd": "0",
          "isChoice": "1",
          "isExistTag": 0,
          "isLading": "2",
          "isQuery": "0",
          "isSign": "0",
          "isSoter": 0,
          "isTimeSet": 0,
          "isUseHandWriteSign": 0,
          "isUsePresetSign": 0,
          "nodeId": "becf3615-0c8e-4e98-8936-483c1c59e6ce",
          "nodeName": "固定会签",
          "nodeRemark": "",
          "nodeSoft": 1,
          "nodeStatus": "1",
          "nodeType": "1",
          "orgId": "b17efb43-292e-4cc9-ac5d-0b46bce059c4",
          "reason": "",
          "refId": "3e900adf-30d3-481f-8f8d-73b4908080d7",
          "upNodeId": "",
          "updateTime": "2018-08-01 18:05:12"
        },
        "nodeId": "",
        "startAuditList": {
          "show": true,
          "selectType": {
            "id": "userId",
            "name": "personName",
            "headpic": "headPic",
            "type": "user"
          },
          "userSelected": [],
          "flowUserList": [
            [
              {
                "attribute": 0,
                "birthday": "",
                "childrenList": [],
                "corpId": "wx05ab253814890c89",
                "createTime": "",
                "departmentName": "",
                "deptId": "",
                "email": "",
                "entryTime": "",
                "headPic": "http://shp.qpic.cn/bizmp/ck4hSGq23Riao6KeuOJ254Qh4K8JHMaPqAKolhy5CVyasJzBbqol3mQ/100",
                "id": "7e0931e06caa320a8606b2348a196844",
                "isTop": 0,
                "leaveTime": "",
                "lunarCalendar": "",
                "mobile": "15259507256",
                "orgId": "b17efb43-292e-4cc9-ac5d-0b46bce059c4",
                "personName": "卢鑫哲",
                "pinyin": "",
                "position": "",
                "sex": "",
                "shorMobile": "",
                "updateTime": "",
                "userId": "7e02a1e06c2a320a8306b3841a286844",
                "userStatus": "2",
                "weixinNum": "",
                "wxUserId": "luxinzhe"
              },
              {
                "attribute": 0,
                "birthday": "",
                "childrenList": [],
                "corpId": "wx05ab253814890c89",
                "createTime": "",
                "departmentName": "",
                "deptId": "",
                "email": "",
                "entryTime": "",
                "headPic": "http://shp.qpic.cn/bizmp/ck4hSGq23RgFSf7iadwB9T1jGibNabgp7VAfPlzoIicces7fJIMICZlDA/100",
                "id": "1dd9da6a-fee9-46eb-864e-53fbca77b96d",
                "isTop": 0,
                "leaveTime": "",
                "lunarCalendar": "",
                "mobile": "15989131328",
                "orgId": "b17efb43-292e-4cc9-ac5d-0b46bce059c4",
                "personName": "陈飞雄",
                "pinyin": "",
                "position": "",
                "sex": "",
                "shorMobile": "",
                "updateTime": "",
                "userId": "cbbf7e9ab38549d3822476feabefdec2",
                "userStatus": "2",
                "weixinNum": "",
                "wxUserId": "qy_15989131328"
              }
            ]
          ],
          "assignRange": true,
          "isCanEdit": true,
          "isCanDelete": true,
          "defaultAllSelect": true
        }
      }
    ],
    "loadLastConfig": {
      "ccPersonList": {
        "type": "1",
        "show": true,
        "name": "加载上次",
        "isGetVal": false
      },
      "toPersonList": {
        "type": "0",
        "show": true,
        "name": "加载上次",
        "isGetVal": false
      }
    },
    "selectConfig": {
      "show": false,
      "signIndex": "user",
      "selectList": {
        "user": {
          "title": "",
          "selectType": "user",
          "userName": "relatives",
          "userSelected": [],
          "deptSelectedShow": false,
          "callBack": {
            "confirm": null
          }
        }
      }
    },
    "ccPersonList": [],
    "flowChioseNodeAuditUser": [],
    "flowChioseNodeAuditUserJson": [],
    "chooseNodeName": "",
    "appointUserIndex": 0,
    "chooseFlowUserJson": "",
    "flowDpIdJson": ""
  }
}
